<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Exceptions</title>

    <!-- Bootstrap -->
    <!-- JQuery is required -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="../css/pandoc-syntax.css">
  </head>
  <body>
<h1 id="coding-bootcamp-exceptions">Coding Bootcamp: Exceptions</h1>
<h2 id="what-is-an-exception">What is an exception?</h2>
<ul>
<li>An exception is an event that occurs when a program runs interapting its normal flow.</li>
</ul>
<h2 id="the-exception-handler">The exception handler</h2>
<ul>
<li><p>We can use the <code>try-catch</code> construct.</p>
<pre class="sourceCode java"><code class="sourceCode java"><span class="kw">try</span> {
    some code here
} <span class="kw">catch</span> and <span class="kw">finally</span> blocks â€¦</code></pre></li>
</ul>
<h2 id="throws">Throws</h2>
<ul>
<li><p>We can declare a might-thrown exception in method signatures.</p>
<pre class="sourceCode java"><code class="sourceCode java"><span class="kw">public</span> <span class="dt">void</span> <span class="fu">writeList</span>() <span class="kw">throws</span> IOException, IndexOutOfBoundsException {...}</code></pre></li>
</ul>
<h2 id="throw-new">Throw new</h2>
<ul>
<li>We can declare a might-throw exception using the <code>throw new</code> keyword.<br /></li>
<li><p>Then, we need to also declare the exception in the method signature (using <code>throws</code>).</p>
<pre class="sourceCode java"><code class="sourceCode java"><span class="kw">if</span> (ammount &lt; <span class="dv">0</span>) {
    <span class="kw">throw</span> <span class="kw">new</span> <span class="fu">NegativeAmmountException</span>();
}</code></pre></li>
</ul>
<h2 id="exception-types">Exception Types</h2>
<p><img src="media/exceptions.png" /></p>
<h2 id="what-is-a-stack-trace">What is a stack trace?</h2>
<ul>
<li>A stack trace is the result of a crashes application<br />and it can inform programs about the cause of the crash.<br /></li>
<li>Use the method <code>printStackTrace()</code> to get a stack trace<br />if a method failed.</li>
</ul>
<h2 id="stack-trace-example">Stack trace example</h2>
<pre class="sourceCode java"><code class="sourceCode java">HighLevelException: MidLevelException: LowLevelException
         at Junk.<span class="fu">a</span>(Junk.<span class="fu">java</span>:<span class="dv">13</span>)
         at Junk.<span class="fu">main</span>(Junk.<span class="fu">java</span>:<span class="dv">4</span>)
 Caused by: MidLevelException: LowLevelException
         at Junk.<span class="fu">c</span>(Junk.<span class="fu">java</span>:<span class="dv">23</span>)
         at Junk.<span class="fu">b</span>(Junk.<span class="fu">java</span>:<span class="dv">17</span>)
         at Junk.<span class="fu">a</span>(Junk.<span class="fu">java</span>:<span class="dv">11</span>)
         <span class="kw">... </span><span class="dv">1</span> more
 Caused by: LowLevelException
         at Junk.<span class="fu">e</span>(Junk.<span class="fu">java</span>:<span class="dv">30</span>)
         at Junk.<span class="fu">d</span>(Junk.<span class="fu">java</span>:<span class="dv">27</span>)
         at Junk.<span class="fu">c</span>(Junk.<span class="fu">java</span>:<span class="dv">21</span>)
         <span class="kw">... </span><span class="dv">3</span> more</code></pre>
<h2 id="create-a-new-exception-class">Create a new exception class</h2>
<ul>
<li>We can create our own exception class by extending an alreading existing exception class e.g. <code>Exception</code>, <code>RuntimeException</code>.</li>
</ul>
<h1 id="best-practices">Best practices</h1>
<ul>
<li>Do not use generic or to specialized exceptions.<br /></li>
<li>Give meaningful names to the new exception class you create.<br /></li>
<li>Alway document your exceptions and explain when the might be thrown.<br /></li>
<li>You should always catch checked exceptions, but also pay attention to unchecked exceptions, too.<br /></li>
<li>Read carefully the documentation of the methods you call from an API and check if they throw exceptions.</li>
</ul>
<h1 id="excercise-1a">Excercise 1a</h1>
<ul>
<li>Create a public class called Bootcamp that has a public static method with the name welcome,<br />which doesn't return any result. Method welcome has one (double) argument.<br />If method argument's value is greater than 25, the method produces an exception called DigitException.<br />Otherwise, the method produces an exception called AnotherDigitException.</li>
</ul>
<h1 id="excercise-1b">Excercise 1b</h1>
<ul>
<li>Class Bootcamp has also a public static method called bye<br />that has no arguments and its type is int. Method bye calls method welcome<br />with argument 299.7 and returns 605 when method welcome produces the exception DigitException<br />and 230 when method welcome produces the exception AnotherDigitException.</li>
</ul>

<hr />
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  </body>
</html>
